CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID INTEGER IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    DOB DATETIME
);

CREATE TABLE IF NOT EXISTS PERSON (
    ID INTEGER IDENTITY PRIMARY KEY,
    FIRSTNAME VARCHAR(100),
    LASTNAME VARCHAR(100),
    BIRTHDAY DATETIME,
    age INT,
    COMMENT VARCHAR(200),
    REMARKS VARCHAR(200)
);